# -*- coding: utf-8 -*-
"""Copy of career-recommendation-system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_5ExD66fVIbpsjSJYXw7uUzi05YzcK0

## **Pengembangan Sistem Berbasis NLP untuk Klasterisasi dan Profiling Aspirasi Karier Mahasiswa**
"""

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import streamlit as st
import seaborn as sns
import base64

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

df = pd.read_excel("Konsultasi Karir_26May26.xlsx")
print("Jumlah Data :", df.shape)
print("\nKolom Dataset:")
print(df.columns)

print("\nSample Data:")
df.head()

df['combined_text'] = (
    df['Dream Job'].astype(str) + " " +
    df['Bidang Minat'].astype(str) + " " +
    df['Rekomendasi Industri 1'].astype(str)
)
print("\nContoh Combined Text:")
print(df['combined_text'].head())

# stopword english dan indonesia
stop_words_id = set(stopwords.words('indonesian'))
stop_words_en = set(stopwords.words('english'))
stop_words = stop_words_id.union(stop_words_en)


# preprocessing
def preprocess_text(text):

    # lowercase
    text = text.lower()

    # hapus angka
    text = re.sub(r'\d+', '', text)

    # hapus simbol
    text = re.sub(r'[^\w\s]', '', text)

    # hapus spasi berlebih
    text = re.sub(r'\s+', ' ', text).strip()

    # tokenization
    tokens = word_tokenize(text)

    # stopword removal + stemming
    clean_tokens = [
        word for word in tokens
        if word not in stop_words
    ]
    return " ".join(clean_tokens)

# preprocessing
df['clean_text'] = df['combined_text'].apply(preprocess_text)

print("\nHasil Preprocessing:")
print(df[['combined_text', 'clean_text']].head())

job_counts = df['Dream Job'].value_counts()

valid_jobs = job_counts[job_counts >= 2].index

df = df[df['Dream Job'].isin(valid_jobs)]

tfidf = TfidfVectorizer(
    lowercase=True,
    stop_words='english',
    max_features=300,
    min_df=3,
    max_df=0.7,
    ngram_range=(1,2)
)

X = tfidf.fit_transform(df['clean_text'])


print("\nShape TF-IDF Matrix:")
print(X.shape)

silhouette_scores = []

range_k = range(2, 10)

print("\n===== HASIL SILHOUETTE SCORE =====")

for k in range_k:

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X)

    score = silhouette_score(X, labels)

    silhouette_scores.append(score)

    print(f"K = {k} --> Silhouette Score = {score:.4f}")

best_k = range_k[np.argmax(silhouette_scores)]

print(f"\nBest K = {best_k}")

# training final model
final_kmeans = KMeans(
    n_clusters=best_k,
    random_state=42,
    n_init=10
)

df['cluster'] = final_kmeans.fit_predict(X)

print("\nSample Hasil Cluster:")
print(
    df[
        [
            'Dream Job',
            'Bidang Minat',
            'cluster'
        ]
    ].head(10)
)

cluster_counts = df['cluster'].value_counts().sort_index()

print("\nDistribusi Cluster:")
print(cluster_counts)

# visualisasi
plt.figure(figsize=(7,5))

cluster_counts.plot(kind='bar')

plt.title("Distribusi Data Tiap Cluster")
plt.xlabel("Cluster")
plt.ylabel("Jumlah Data")

plt.xticks(rotation=0)
plt.show()

terms = tfidf.get_feature_names_out()

order_centroids = final_kmeans.cluster_centers_.argsort()[:, ::-1]

print("\n===== TOP KEYWORDS TIAP CLUSTER =====\n")

for i in range(best_k):

    print(f"Cluster {i}")

    top_words = []

    for ind in order_centroids[i, :10]:
        top_words.append(terms[ind])

    print(", ".join(top_words))
    print("-" * 50)

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# menyimpan inertia
inertia = []

# range jumlah cluster
k = range(1, 11)

# hitung inertia tiap k
for i in k:
    kmeans = KMeans(
        n_clusters=i,
        random_state=42,
        n_init=10
    )

    kmeans.fit(X)

    inertia.append(kmeans.inertia_)

# plot elbow method
plt.figure(figsize=(8,5))

plt.plot(k, inertia, marker='o')

plt.xlabel('Jumlah Cluster')
plt.ylabel('Inertia')
plt.title('Elbow Method')

plt.show()

from sklearn.decomposition import PCA

# PCA 2 dimensi
pca = PCA(n_components=2)

# transform TF-IDF ke PCA
X_pca = pca.fit_transform(X.toarray())

# transform centroid KMeans
centroids_pca = pca.transform(final_kmeans.cluster_centers_)

plt.figure(figsize=(10,7))

scatter = plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=df['cluster'],
    cmap='tab10',
    alpha=0.7
)

plt.colorbar(scatter)

plt.scatter(
    centroids_pca[:,0],
    centroids_pca[:,1],
    s=300,
    c='black',
    marker='X',
    label='Centroid'
)

cluster_names = {
    0: 'Business & Consulting',
    1: 'Finance & Banking',
    2: 'Tech & Data',
    3: 'Education & Healthcare',
    4: 'Creative & Digital'
}

for i, (x, y) in enumerate(centroids_pca):

    plt.text(
        x,
        y,
        cluster_names[i],
        fontsize=10,
        weight='bold'
    )

plt.title('Visualisasi PCA K-Means Clustering')

plt.xlabel('PCA 1')
plt.ylabel('PCA 2')

plt.grid(True)
plt.legend()

plt.show()

print(df['cluster'].unique())

from sklearn.metrics.pairwise import euclidean_distances
import pandas as pd

cluster_names = {
    0: 'Business & Consulting',
    1: 'Finance & Banking',
    2: 'Tech & Data',
    3: 'Education & Healthcare',
    4: 'Creative & Digital'
}

# gunakan model FINAL
centroids = final_kmeans.cluster_centers_

# hitung jarak antar centroid
distance_matrix = euclidean_distances(centroids)

cluster_labels = list(cluster_names.values())

# dataframe
distance_df = pd.DataFrame(
    distance_matrix,
    columns=cluster_labels,
    index=cluster_labels
)

print(distance_df)

plt.figure(figsize=(8,6))

sns.heatmap(
    distance_df,
    annot=True,
    cmap='Blues',
    fmt='.2f'
)

plt.title('Jarak Antar Cluster')
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

cluster_col = 'cluster'
text_col = 'clean_text'

# jumlah cluster
clusters = sorted(df[cluster_col].unique())

# membuat subplot
fig, axes = plt.subplots(len(clusters), 1, figsize=(12, 5 * len(clusters)))

# jika cluster cuma 1
if len(clusters) == 1:
    axes = [axes]

for ax, clust in zip(axes, clusters):

    # gabungkan semua text dalam cluster
    text = " ".join(
        df[df[cluster_col] == clust][text_col]
        .dropna()
        .astype(str)
    )

    # buat wordcloud
    wordcloud = WordCloud(
        width=1000,
        height=500,
        background_color='white',
        colormap='viridis'
    ).generate(text)

    # tampilkan
    ax.imshow(wordcloud, interpolation='bilinear')
    ax.set_title(f'Word Cloud Cluster {clust}', fontsize=16)
    ax.axis('off')

plt.tight_layout()
plt.show()

import seaborn as sns

text_col = 'clean_text'

# menghitung jumlah kata
df['word_count'] = df[text_col].astype(str).apply(lambda x: len(x.split()))

# menghitung panjang karakter
df['char_count'] = df[text_col].astype(str).apply(len)

# =========================================================
# HISTOGRAM JUMLAH KATA
# =========================================================

plt.figure(figsize=(10,5))

sns.histplot(df['word_count'], bins=30, kde=True)

plt.title('Distribusi Jumlah Kata')
plt.xlabel('Jumlah Kata')
plt.ylabel('Frekuensi')

plt.show()

from collections import Counter

text_col = 'clean_text'

# gabungkan semua text
all_text = " ".join(df[text_col].dropna().astype(str))

# split kata
words = all_text.split()

# hitung frekuensi kata
word_freq = Counter(words)

# ambil 20 kata teratas
top_words = word_freq.most_common(20)

# ubah ke dataframe
top_words_df = pd.DataFrame(top_words, columns=['Word', 'Frequency'])

# =========================================================
# PLOT
# =========================================================

plt.figure(figsize=(12,6))

sns.barplot(
    data=top_words_df,
    x='Frequency',
    y='Word'
)

plt.title('20 Kata Paling Sering Muncul')
plt.xlabel('Frekuensi')
plt.ylabel('Kata')

plt.show()

df.to_csv("hasil_cluster_dream_job.csv", index=False)

print("\nFile hasil berhasil disimpan!")

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

# =========================================================
# PAGE CONFIG
# =========================================================

st.set_page_config(
    page_title="Career Recommendation System",
    layout="wide"
)

# =========================================================
# SIDEBAR
# =========================================================
st.markdown("""
<style>
[data-testid="stSidebar"] {
    background-color: #3b3a84;
}

/* warna teks sidebar */
[data-testid="stSidebar"] * {
    color: white;
}
</style>
""", unsafe_allow_html=True)
st.sidebar.title("🎯 Career Recommendation System")

st.sidebar.info("""
### Model yang Digunakan
- Natural Language Processing
- K-Means Clustering
""")

st.sidebar.info("""
### Hasil Analisis
- Kategori Pekerjaan Impian
- Rekomendasi Pekerjaan
- Analisis Kecocokan Cluster
- Analisis Profil
""")

st.markdown("""
<style>
.stApp {
    background: linear-gradient(to right, #effcff, #8988ff);
}
</style>
""", unsafe_allow_html=True)

# =========================================================
# TITLE
# =========================================================
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@500;700&display=swap');

[data-testid="stTitle"] {
    font-family: 'Montserrat', sans-serif;
    font-size: 42px;
    font-weight: 700;
    background: linear-gradient(to right, #2c2b67, #3b3a84);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}
</style>
""", unsafe_allow_html=True)

st.title("Career Recommendation System")

st.markdown("""
Sistem rekomendasi pekerjaan berbasis
**K-Means Clustering + NLP**
""")

# =========================================================
# INPUT USER
# =========================================================

st.subheader("📝 Isi Profil Karier Kamu")

dream_job = st.text_area(
    "Dream Job / Pekerjaan Impian",
    placeholder="Contoh: data analyst, software engineer, UI/UX designer"
)

interest = st.text_area(
    "Minat & Bakat",
    placeholder="Contoh: suka analisis data, desain, coding, bisnis"
)

# =========================================================
# NORMALISASI TEKS
# =========================================================

def preprocess(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z\\s]', '', text)

    return text

# =========================================================
# RULE-BASED CLUSTERING
# =========================================================

def predict_cluster(text):

    text = preprocess(text)

    # =====================================================
    # KEYWORDS
    # =====================================================

    business_keywords = [
        'business',
        'management',
        'consulting',
        'leader',
        'startup',
        'entrepreneur',
        'strategy'
    ]

    finance_keywords = [
        'finance',
        'bank',
        'investment',
        'accounting',
        'economics',
        'financial',
        'trading',
        'stock'
    ]

    tech_keywords = [
        'data',
        'analyst',
        'python',
        'coding',
        'programming',
        'software',
        'machine learning',
        'ai',
        'developer',
        'web'
    ]

    edu_keywords = [
        'teacher',
        'education',
        'health',
        'doctor',
        'psychology',
        'government',
        'trainer'
    ]

    creative_keywords = [
        'design',
        'creative',
        'ui',
        'ux',
        'video',
        'editing',
        'content',
        'social media',
        'marketing'
    ]

    # =====================================================
    # SCORE
    # =====================================================

    scores = {
        'Tech & Data': 0,
        'Finance & Banking': 0,
        'Creative & Digital': 0,
        'Business & Consulting': 0,
        'Education & Healthcare': 0
    }

    detected_keywords = []

    # =====================================================
    # HITUNG SCORE
    # =====================================================

    for word in tech_keywords:
        if word in text:
            scores['Tech & Data'] += 1
            detected_keywords.append(word)

    for word in finance_keywords:
        if word in text:
            scores['Finance & Banking'] += 1
            detected_keywords.append(word)

    for word in creative_keywords:
        if word in text:
            scores['Creative & Digital'] += 1
            detected_keywords.append(word)

    for word in business_keywords:
        if word in text:
            scores['Business & Consulting'] += 1
            detected_keywords.append(word)

    for word in edu_keywords:
        if word in text:
            scores['Education & Healthcare'] += 1
            detected_keywords.append(word)

    # =====================================================
    # BEST CLUSTER
    # =====================================================

    best_cluster = max(scores, key=scores.get)

    best_score = max(scores.values())

    total_score = sum(scores.values())

    confidence = round(
        (best_score / total_score) * 100,
        2
    ) if total_score > 0 else 0

    return best_cluster, scores, confidence, detected_keywords

# =========================================================
# CAREER RECOMMENDATION
# =========================================================

career_recommendation = {

    'Tech & Data': [
        'Data Analyst',
        'Data Scientist',
        'Software Engineer',
        'AI Engineer',
        'Business Intelligence'
    ],

    'Finance & Banking': [
        'Financial Analyst',
        'Investment Banker',
        'Accountant',
        'Risk Analyst',
        'Auditor'
    ],

    'Creative & Digital': [
        'UI/UX Designer',
        'Graphic Designer',
        'Digital Marketing',
        'Content Creator',
        'Social Media Specialist'
    ],

    'Business & Consulting': [
        'Business Analyst',
        'Management Consultant',
        'Project Manager',
        'Entrepreneur',
        'Startup Strategist'
    ],

    'Education & Healthcare': [
        'Teacher',
        'Psychologist',
        'Healthcare Analyst',
        'Trainer',
        'Government Staff'
    ]
}

# =========================================================
# CLUSTER DESCRIPTION
# =========================================================

career_description = {

    'Tech & Data':
    'Bidang yang berfokus pada teknologi, data, AI, dan software.',

    'Finance & Banking':
    'Bidang yang berkaitan dengan keuangan, investasi, dan perbankan.',

    'Creative & Digital':
    'Bidang kreatif seperti desain, content creation, dan digital media.',

    'Business & Consulting':
    'Bidang manajemen, bisnis, strategi, dan consulting.',

    'Education & Healthcare':
    'Bidang pendidikan, kesehatan, dan pelayanan masyarakat.'
}

# =========================================================
# ICON
# =========================================================

cluster_icons = {
    'Tech & Data': '💻',
    'Finance & Banking': '💰',
    'Creative & Digital': '🎨',
    'Business & Consulting': '📈',
    'Education & Healthcare': '🏥'
}

# =========================================================
# BUTTON
# =========================================================

if st.button("🔍 Cari Pekerjaan yang Cocok"):

    user_text = dream_job + " " + interest

    cluster, scores, confidence, detected_keywords = predict_cluster(user_text)

    recommendations = career_recommendation[cluster]

    # =====================================================
    # HASIL
    # =====================================================

    st.success(
        f"{cluster_icons[cluster]} Cluster Kamu: {cluster}"
    )

    # =====================================================
    # CONFIDENCE SCORE
    # =====================================================

    st.metric(
        "🎯 Tingkat Kecocokan",
        f"{confidence}%"
    )

    # =====================================================
    # DESKRIPSI
    # =====================================================

    st.info(career_description[cluster])

    # =====================================================
    # REKOMENDASI PEKERJAAN
    # =====================================================

    st.subheader("💼 Rekomendasi Pekerjaan")

    for job in recommendations:

        st.markdown(f"- ✅ {job}")

    # =====================================================
    # KEYWORD TERDETEKSI
    # =====================================================

    st.subheader("🧠 Keyword Terdeteksi")

    if len(detected_keywords) > 0:

        for word in detected_keywords:

            st.markdown(f"- {word}")

    else:

        st.write("Tidak ada keyword yang terdeteksi.")

    # =====================================================
    # VISUALISASI SCORE
    # =====================================================

    st.subheader("📊 Analisis Skor Cluster")

    score_df = pd.DataFrame({
        'Cluster': list(scores.keys()),
        'Score': list(scores.values())
    })

    st.bar_chart(
        score_df.set_index('Cluster')
    )

    # =====================================================
    # INFO TAMBAHAN
    # =====================================================

    st.subheader("📌 Analisis Profil")

    st.write(f"""
    Berdasarkan teks yang dimasukkan, sistem mendeteksi
    kecenderungan minat karier pada bidang
    **{cluster}** dengan tingkat kecocokan
    sebesar **{confidence}%**.
    """)

# =========================================================
# FOOTER
# =========================================================

st.markdown("---")

st.caption(
    "Career Recommendation System | NLP Project"
)
